### ISSUE TITLE
【課題】221105 && 再開までの進捗共有

### ISSUE THREAD

**Issue by technicakidz** [dsuke0526/original-app#28]
### 背景

star rating 機能の実装方針転換。
https://github.com/dsuke0526/original-app/issues/26#issuecomment-1304537797

### TODO

- [x] [django-star-rating](https://github.com/dsuke0526/original-app/issues/26#issuecomment-1304537797) を参考に実装を進める 
- [x]  (余力あれば)ログイン機能 各種ログイン機能の実装タスクリスト  #2 の実装着手

**Comment by dsuke0526** [comment]
![スクリーンショット (54)](https://user-images.githubusercontent.com/108209803/200769036-2a54c876-48bb-4882-bcf9-eab7b4692f11.png)
![スクリーンショット (53)](https://user-images.githubusercontent.com/108209803/200769056-6a694148-4587-4651-af03-eecc2e503ffc.png)

前に講義中にコマンドプロンプトにてさわったところがエラー出てると思っているんですがやり方を忘れてしまったので
教えていたただきたいです。

**Comment by technicakidz** [comment]
以下のような流れでテーブルを追加します。
cf. https://tutorial.djangogirls.org/ja/django_models/#%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AB%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B

models.py に下記のようなクラスを追加
```
class Hoge(models.Model):
    hoge = models.TextField()
```

その後、コマンドプロンプトを実行
```
$ python manage.py makemigrations
$ python manage.py migrate blog
```

**Comment by technicakidz** [comment]
講義再開までの進捗共有場所はここのコメントでできればと思います．
